export const SET_TITLE = "SET_TITLE";

// shopping cart
export const ADD_QUANTITY_ITEM_SHOPPING = "ADD_QUANTITY_ITEM_SHOPPING";
export const REMOVE_QUANTITY_ITEM_SHOPPING = "REMOVE_QUANTITY_ITEM_SHOPPING";
export const DELETE_ITEM_SHOPPING = "DELETE_ITEM_SHOPPING";
export const GET_SHOPPING_CART = "GET_SHOPPING_CART";
export const SET_KEYWORD = "SET_KEYWORD";
export const SET_STATUS = "SET_STATUS";
